return {
  { "sainnhe/gruvbox-material" },
  { "martinda/Jenkinsfile-vim-syntax" },
  { "jeetsukumaran/vim-indentwise" },
  { "mbbill/undotree" },
  { "tpope/vim-commentary" },
  { "tpope/vim-repeat" },
  { "tpope/vim-surround" },
  { "tpope/vim-rsi" },
  { "elixir-editors/vim-elixir" },
  { "honza/vim-snippets" },
  { "andrewstuart/vim-kubernetes" },
  { "avdgaag/vim-phoenix" },
  { "rafamadriz/friendly-snippets" },
}
